import {
  AtSign,
  Check,
  ChevronDown,
  ChevronsLeftRight,
  CircleHelp,
  ClipboardList,
  Copy,
  Cpu,
  Droplets,
  Eye,
  FileText,
  Flag,
  Gift,
  Globe2,
  Gauge,
  Link2,
  Monitor,
  RefreshCw,
  Search,
  ShieldCheck,
  Smile,
  Sparkles,
  TriangleAlert,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const onceUiIcons: Record<string, LucideIcon> = {
  chevronDown: ChevronDown,
  sparkle: Sparkles,
  gift: Gift,
  chevronsLeftRight: ChevronsLeftRight,
  security: ShieldCheck,
  eye: Eye,
  document: FileText,
  symbol: AtSign,
  copy: Copy,
  link: Link2,
  screen: Monitor,
  computer: Cpu,
  check: Check,
  world: Globe2,
  refresh: RefreshCw,
  radialGauge: Gauge,
  search: Search,
  opacity: Droplets,
  warning: TriangleAlert,
  smiley: Smile,
  flag: Flag,
  clipboard: ClipboardList,
  help: CircleHelp,
};
